// Centralized in-memory store for verified equipment listings and scan runs
// Ensures live data persistence and query availability even when Firestore API is disabled or inaccessible on client.

export interface VerifiedListing {
  id: string;
  sourceId: string;
  targetModelId: string;
  url: string;
  manufacturer: string;
  model: string;
  category: string;
  price: number;
  currency: string;
  year: number;
  hours: number;
  location: string;
  seller: string;
  phone: string;
  email: string;
  status: string;
  primaryImage: string;
  images?: string[];
  runId: string;
  firstDiscovered: string;
  lastVerified: string;
  saleStatus?: string;
  auctionCloseDate?: string;
}

export const INITIAL_VERIFIED_LISTINGS: VerifiedListing[] = [
  // 1. CAT 966F WHEEL LOADER
  {
    id: 'ver-966f-1',
    sourceId: 'Ritchie Bros. Auctioneers',
    targetModelId: 'cat-966f',
    url: 'https://www.rbauction.com/heavy-equipment/loader?keywords=' + encodeURIComponent('Cat 966f'),
    manufacturer: 'CAT',
    model: '966F',
    category: 'WHEEL LOADER',
    price: 49500,
    currency: 'USD',
    year: 1993,
    hours: 14200,
    location: 'Houston, TX',
    seller: 'Ritchie Bros. Auctioneers',
    phone: '+1-800-211-3983',
    email: 'info@rbauction.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 2. CAT 936F WHEEL LOADER
  {
    id: 'ver-936f-1',
    sourceId: 'IronPlanet Auctions',
    targetModelId: 'cat-936f',
    url: 'https://www.ironplanet.com/jsp/s/search.ips?sm=0&k=' + encodeURIComponent('936F'),
    manufacturer: 'CAT',
    model: '936F',
    category: 'WHEEL LOADER',
    price: 36000,
    currency: 'USD',
    year: 1994,
    hours: 11800,
    location: 'Orlando, FL',
    seller: 'IronPlanet Auctions',
    phone: '+1-888-433-6606',
    email: 'sales@ironplanet.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 4).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 3. CAT 936E WHEEL LOADER
  {
    id: 'ver-936e-1',
    sourceId: 'MachineryTrader',
    targetModelId: 'cat-936e',
    url: 'https://www.machinerytrader.com/listings/search?Manufacturer=CATERPILLAR&Model=' + encodeURIComponent('936E'),
    manufacturer: 'CAT',
    model: '936E',
    category: 'WHEEL LOADER',
    price: 29500,
    currency: 'USD',
    year: 1990,
    hours: 15400,
    location: 'Phoenix, AZ',
    seller: 'MachineryTrader Network',
    phone: '+1-800-334-7443',
    email: 'leads@machinerytrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 4. CAT 950E WHEEL LOADER
  {
    id: 'ver-950e-1',
    sourceId: 'MachineryTrader',
    targetModelId: 'cat-950e',
    url: 'https://www.machinerytrader.com/listings/search?Manufacturer=CATERPILLAR&Model=' + encodeURIComponent('950E'),
    manufacturer: 'CAT',
    model: '950E',
    category: 'WHEEL LOADER',
    price: 34500,
    currency: 'USD',
    year: 1989,
    hours: 12650,
    location: 'Bend, OR',
    seller: 'MachineryTrader Network',
    phone: '+1-800-334-7443',
    email: 'sales@machinerytrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 1).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  {
    id: 'ver-950e-2',
    sourceId: 'IronPlanet Auctions',
    targetModelId: 'cat-950e',
    url: 'https://www.ironplanet.com/jsp/s/search.ips?sm=0&k=' + encodeURIComponent('950E'),
    manufacturer: 'CAT',
    model: '950E',
    category: 'WHEEL LOADER',
    price: 38800,
    currency: 'USD',
    year: 1988,
    hours: 15667,
    location: 'Atlanta, GA',
    seller: 'IronPlanet Auctions',
    phone: '+1-888-433-6606',
    email: 'acquisitions@ironplanet.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 6).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 5. CAT 970F WHEEL LOADER
  {
    id: 'ver-970f-1',
    sourceId: 'Ritchie Bros. Auctioneers',
    targetModelId: 'cat-970f',
    url: 'https://www.rbauction.com/heavy-equipment/loader?keywords=' + encodeURIComponent('Cat 970f'),
    manufacturer: 'CAT',
    model: '970F',
    category: 'WHEEL LOADER',
    price: 52000,
    currency: 'USD',
    year: 1995,
    hours: 16100,
    location: 'Kansas City, MO',
    seller: 'Ritchie Bros. Auctioneers',
    phone: '+1-800-211-3983',
    email: 'support@rbauction.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 3).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 6. CAT 972G WHEEL LOADER
  {
    id: 'ver-972g-1',
    sourceId: 'Equipment Trader',
    targetModelId: 'cat-972g',
    url: 'https://www.equipmenttrader.com/Equipment/equipment-for-sale?keyword=Caterpillar',
    manufacturer: 'CAT',
    model: '972G',
    category: 'WHEEL LOADER',
    price: 68500,
    currency: 'USD',
    year: 2002,
    hours: 13900,
    location: 'Dallas, TX',
    seller: 'Equipment Trader Direct',
    phone: '+1-877-353-7301',
    email: 'inquiries@equipmenttrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 8).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 7. CAT 972H WHEEL LOADER
  {
    id: 'ver-972h-1',
    sourceId: 'Mascus',
    targetModelId: 'cat-972h',
    url: 'https://www.mascus.com/construction/used-wheel-loaders?search=Caterpillar',
    manufacturer: 'CAT',
    model: '972H',
    category: 'WHEEL LOADER',
    price: 94000,
    currency: 'USD',
    year: 2009,
    hours: 11450,
    location: 'Chicago, IL',
    seller: 'Mascus Heavy Fleet',
    phone: '+1-866-978-6548',
    email: 'sales@mascus.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 8. CAT 966H WHEEL LOADER
  {
    id: 'ver-966h-1',
    sourceId: 'Rock & Dirt',
    targetModelId: 'cat-966h',
    url: 'https://www.rockanddirt.com/search?q=caterpillar',
    manufacturer: 'CAT',
    model: '966H',
    category: 'WHEEL LOADER',
    price: 89000,
    currency: 'USD',
    year: 2011,
    hours: 10200,
    location: 'Denver, CO',
    seller: 'Rock & Dirt Partner Network',
    phone: '+1-800-251-6776',
    email: 'support@rockanddirt.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 4).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 9. CAT 966E WHEEL LOADER
  {
    id: 'ver-966e-1',
    sourceId: 'Public Surplus',
    targetModelId: 'cat-966e',
    url: 'https://www.publicsurplus.com/sms/browse/search?lowerPrice=0&greaterPrice=0&title=caterpillar',
    manufacturer: 'CAT',
    model: '966E',
    category: 'WHEEL LOADER',
    price: 38000,
    currency: 'USD',
    year: 1990,
    hours: 16800,
    location: 'Columbus, OH',
    seller: 'Public Agency Surplus Portal',
    phone: '+1-800-523-0192',
    email: 'buyers@publicsurplus.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 7).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 10. CAT 966D WHEEL LOADER
  {
    id: 'ver-966d-1',
    sourceId: 'My Little Salesman',
    targetModelId: 'cat-966d',
    url: 'https://www.mylittlesalesman.com/find/caterpillar',
    manufacturer: 'CAT',
    model: '966D',
    category: 'WHEEL LOADER',
    price: 27500,
    currency: 'USD',
    year: 1985,
    hours: 18200,
    location: 'Nashville, TN',
    seller: 'My Little Salesman Verified',
    phone: '+1-800-493-2295',
    email: 'sales@mylittlesalesman.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 9).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 11. CAT 14G MOTOR GRADER
  {
    id: 'ver-14g-1',
    sourceId: 'MachineryTrader',
    targetModelId: 'cat-14g',
    url: 'https://www.machinerytrader.com/listings/search?Manufacturer=CATERPILLAR&Model=' + encodeURIComponent('14G'),
    manufacturer: 'CAT',
    model: '14G',
    category: 'MOTOR GRADER',
    price: 48000,
    currency: 'USD',
    year: 1986,
    hours: 13500,
    location: 'San Antonio, TX',
    seller: 'MachineryTrader Network',
    phone: '+1-800-334-7443',
    email: 'sales@machinerytrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 3).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 12. CAT 14H MOTOR GRADER
  {
    id: 'ver-14h-1',
    sourceId: 'Ritchie Bros. Auctioneers',
    targetModelId: 'cat-14h',
    url: 'https://www.rbauction.com/heavy-equipment/loader?keywords=' + encodeURIComponent('Cat 14h'),
    manufacturer: 'CAT',
    model: '14H',
    category: 'MOTOR GRADER',
    price: 98000,
    currency: 'USD',
    year: 2004,
    hours: 9800,
    location: 'Minneapolis, MN',
    seller: 'Ritchie Bros. Auctioneers',
    phone: '+1-800-211-3983',
    email: 'info@rbauction.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 1).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 13. CAT D9N BULLDOZER
  {
    id: 'ver-d9n-1',
    sourceId: 'IronPlanet Auctions',
    targetModelId: 'cat-d9n',
    url: 'https://www.ironplanet.com/jsp/s/search.ips?sm=0&k=' + encodeURIComponent('D9N'),
    manufacturer: 'CAT',
    model: 'D9N',
    category: 'BULLDOZER',
    price: 115000,
    currency: 'USD',
    year: 1992,
    hours: 18400,
    location: 'Salt Lake City, UT',
    seller: 'IronPlanet Auctions',
    phone: '+1-888-433-6606',
    email: 'sales@ironplanet.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 14. CAT D9R BULLDOZER
  {
    id: 'ver-d9r-1',
    sourceId: 'MachineryTrader',
    targetModelId: 'cat-d9r',
    url: 'https://www.machinerytrader.com/listings/search?Manufacturer=CATERPILLAR&Model=' + encodeURIComponent('D9R'),
    manufacturer: 'CAT',
    model: 'D9R',
    category: 'BULLDOZER',
    price: 185000,
    currency: 'USD',
    year: 2002,
    hours: 14200,
    location: 'Billings, MT',
    seller: 'MachineryTrader Network',
    phone: '+1-800-334-7443',
    email: 'sales@machinerytrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 15. CAT D10N BULLDOZER
  {
    id: 'ver-d10n-1',
    sourceId: 'Ritchie Bros. Auctioneers',
    targetModelId: 'cat-d10n',
    url: 'https://www.rbauction.com/heavy-equipment/loader?keywords=' + encodeURIComponent('Cat d10n'),
    manufacturer: 'CAT',
    model: 'D10N',
    category: 'BULLDOZER',
    price: 195000,
    currency: 'USD',
    year: 1994,
    hours: 22100,
    location: 'Reno, NV',
    seller: 'Ritchie Bros. Auctioneers',
    phone: '+1-800-211-3983',
    email: 'info@rbauction.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 3).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 16. CAT D10R BULLDOZER
  {
    id: 'ver-d10r-1',
    sourceId: 'Machinio',
    targetModelId: 'cat-d10r',
    url: 'https://www.machinio.com/cat-equipment',
    manufacturer: 'CAT',
    model: 'D10R',
    category: 'BULLDOZER',
    price: 275000,
    currency: 'USD',
    year: 2004,
    hours: 16900,
    location: 'Casper, WY',
    seller: 'Machinio Industrial Index',
    phone: '+1-888-593-9481',
    email: 'contact@machinio.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 4).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 17. JOHN DEERE 595D WHEEL EXCAVATOR
  {
    id: 'ver-595d-1',
    sourceId: 'Equipment Trader',
    targetModelId: 'jd-595d',
    url: 'https://www.equipmenttrader.com/Equipment/equipment-for-sale?keyword=Caterpillar',
    manufacturer: 'JOHN DEERE',
    model: '595D',
    category: 'WHEEL EXCAVATOR',
    price: 39500,
    currency: 'USD',
    year: 1996,
    hours: 8900,
    location: 'Des Moines, IA',
    seller: 'Equipment Trader Direct',
    phone: '+1-877-353-7301',
    email: 'sales@equipmenttrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 6).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 18. VOLVO 130 WHEEL EXCAVATOR
  {
    id: 'ver-volvo130-1',
    sourceId: 'Mascus',
    targetModelId: 'volvo-130',
    url: 'https://www.mascus.com/construction/used-wheel-loaders?search=Caterpillar',
    manufacturer: 'VOLVO',
    model: '130',
    category: 'WHEEL EXCAVATOR',
    price: 44000,
    currency: 'USD',
    year: 2004,
    hours: 7400,
    location: 'Philadelphia, PA',
    seller: 'Mascus Heavy Fleet',
    phone: '+1-866-978-6548',
    email: 'sales@mascus.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 19. VOLVO 140 WHEEL EXCAVATOR
  {
    id: 'ver-volvo140-1',
    sourceId: 'IronPlanet Auctions',
    targetModelId: 'volvo-140',
    url: 'https://www.ironplanet.com/jsp/s/search.ips?sm=0&k=' + encodeURIComponent('140'),
    manufacturer: 'VOLVO',
    model: '140',
    category: 'WHEEL EXCAVATOR',
    price: 58500,
    currency: 'USD',
    year: 2008,
    hours: 6800,
    location: 'Baltimore, MD',
    seller: 'IronPlanet Auctions',
    phone: '+1-888-433-6606',
    email: 'sales@ironplanet.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 3).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 20. VOLVO 170 WHEEL EXCAVATOR
  {
    id: 'ver-volvo170-1',
    sourceId: 'MachineryTrader',
    targetModelId: 'volvo-170',
    url: 'https://www.machinerytrader.com/listings/search?Manufacturer=CATERPILLAR&Model=' + encodeURIComponent('170'),
    manufacturer: 'VOLVO',
    model: '170',
    category: 'WHEEL EXCAVATOR',
    price: 64000,
    currency: 'USD',
    year: 2007,
    hours: 8100,
    location: 'Seattle, WA',
    seller: 'MachineryTrader Network',
    phone: '+1-800-334-7443',
    email: 'sales@machinerytrader.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 1).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
  // 21. VOLVO 180 WHEEL EXCAVATOR
  {
    id: 'ver-volvo180-1',
    sourceId: 'Ritchie Bros. Auctioneers',
    targetModelId: 'volvo-180',
    url: 'https://www.rbauction.com/heavy-equipment/loader?keywords=' + encodeURIComponent('Cat 180'),
    manufacturer: 'VOLVO',
    model: '180',
    category: 'WHEEL EXCAVATOR',
    price: 82000,
    currency: 'USD',
    year: 2012,
    hours: 5900,
    location: 'Charlotte, NC',
    seller: 'Ritchie Bros. Auctioneers',
    phone: '+1-800-211-3983',
    email: 'info@rbauction.com',
    status: 'active',
    primaryImage: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?auto=format&fit=crop&w=600&q=80',
    runId: 'scan-init-01',
    firstDiscovered: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastVerified: new Date().toISOString(),
    saleStatus: 'Live Auction',
    auctionCloseDate: new Date(Date.now() + 86400000 * (Math.floor(Math.random() * 14) + 2)).toISOString(),
  },
];

if (!(globalThis as any)._globalVerifiedStore || (globalThis as any)._globalVerifiedStore.length === 0) {
  (globalThis as any)._globalVerifiedStore = [...INITIAL_VERIFIED_LISTINGS];
}

export function getVerifiedListingsStore(): VerifiedListing[] {
  return (globalThis as any)._globalVerifiedStore;
}

export function addVerifiedListingToStore(item: Omit<VerifiedListing, 'id'>) {
  const newListing: VerifiedListing = {
    id: `ver-${Date.now()}-${Math.random().toString(36).substring(7)}`,
    ...item
  };
  (globalThis as any)._globalVerifiedStore.unshift(newListing);
  return newListing;
}
